all-policies: false
allow-self-signed: false
api-url: https://api.gitguardian.com
exit-zero: false
matches-ignore:
- match: 59d5a3bce66804e5749a2e294812a2f9dc93b250590a1f7a7f4f16298f7ca585
  name: Generic Password - sample.json
paths-ignore: []
show-secrets: false
verbose: false
